2018-06-01 15:54:55,479 ERROR: Exception on /user/backyard raised bed, 14/delete [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\GardenApp\app\main\routes.py", line 216, in delete_garden
    form = DeleteGardenForm()
NameError: name 'DeleteGardenForm' is not defined
2018-06-01 15:55:31,920 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-06-01 15:55:53,811 ERROR: Exception on /registerGarden [POST] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\GardenApp\app\main\routes.py", line 177, in registerGarden
    lat = responseJSON['results'][0]['geometry']['location']['lat']
IndexError: list index out of range
2018-06-01 15:58:40,142 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-06-01 16:01:16,221 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-06-01 16:02:48,550 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-06-01 16:06:30,014 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-06-01 16:08:29,085 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-06-01 16:10:05,186 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-06-01 16:10:27,935 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-06-01 16:10:45,694 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-06-01 16:13:40,095 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-06-01 16:15:16,957 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-06-01 16:15:44,117 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
