2018-05-18 15:10:13,601 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-18 15:11:28,379 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-18 15:17:19,074 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-18 15:45:00,675 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-18 17:34:54,024 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-18 17:40:06,617 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-18 17:40:14,252 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-18 17:40:54,110 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-18 17:44:18,133 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-18 17:44:35,261 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 15:40:05,782 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 15:40:42,859 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 15:41:26,756 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 15:42:36,765 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 15:42:54,639 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 15:45:44,123 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 15:48:14,395 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 15:49:18,628 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 15:50:07,972 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 15:57:05,150 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 17:49:36,691 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 17:50:19,509 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 17:51:04,578 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 17:56:33,169 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 17:57:27,160 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 17:58:47,177 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 17:58:49,746 ERROR: Exception on /index [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\GardenApp\app\main\routes.py", line 49, in index
    markers= markers,
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_googlemaps\__init__.py", line 54, in __init__
    self.build_markers(markers)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_googlemaps\__init__.py", line 94, in build_markers
    self.add_marker(**marker)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_googlemaps\__init__.py", line 117, in add_marker
    raise AttributeError('lat and lng required')
AttributeError: lat and lng required
2018-05-21 17:59:52,745 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 18:00:19,750 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 18:05:27,565 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:01:13,353 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:01:16,318 ERROR: Exception on /index [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\GardenApp\app\main\routes.py", line 59, in index
    posts_next_url=posts_next_url, posts_prev_url=posts_prev_url, plants=plants.items,
AttributeError: 'list' object has no attribute 'items'
2018-05-21 19:02:16,470 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:02:47,625 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:03:26,954 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:04:42,342 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:13:38,023 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:15:52,452 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:17:10,008 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:18:22,949 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:18:54,726 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:21:25,949 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:24:38,391 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:27:29,103 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:29:37,808 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:31:01,066 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:32:02,029 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:34:44,613 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:36:44,039 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:37:25,434 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:40:01,829 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:41:30,290 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-21 19:47:30,784 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-29 15:39:16,499 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-29 15:39:32,013 ERROR: Exception on /index [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\GardenApp\app\main\routes.py", line 49, in index
    location_for_markers[index][2].extend(garden_plants)
TypeError: 'float' object is not subscriptable
2018-05-29 15:44:21,993 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
2018-05-29 15:44:26,060 ERROR: Exception on /index [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\GardenApp\app\main\routes.py", line 74, in index
    posts_next_url=posts_next_url, posts_prev_url=posts_prev_url, plants=plants.items,
AttributeError: 'list' object has no attribute 'items'
2018-05-29 15:46:00,541 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:73]
